CREATE USER 'digitalfish'@localhost IDENTIFIED BY 'DigitalFish!';
GRANT USAGE ON *.* TO 'digitalfish'@localhost;
GRANT SELECT, EXECUTE, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, LOCK TABLES  ON `digitalfish`.* TO 'digitalfish'@'%';
FLUSH PRIVILEGES;
SHOW GRANTS FOR 'digitalfish'@localhost;